version: '3'
services:
  tujr-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'tujr'
      MYSQL_PASSWORD: 'tujr'
      MYSQL_INITDB_SKIP_TZINFO: 1  # Skip tzinfo setup to avoid warning
      MYSQL_LOWER_CASE_TABLE_NAMES: 1
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    restart: always
    container_name: mysql8.0.31
    image: mysql:8.0.31
    ports:
      - 3306:3306
    privileged: true
    command: [ "mysqld", "--init-file", "/docker-entrypoint-initdb.d/init.sql",
               "--explicit_defaults_for_timestamp=true",
               "--lower_case_table_names=1",
               "--default-authentication-plugin=mysql_native_password" ]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring_cloud_default

  tujr-redis:
    image: redis:7.0.0
    ports:
      - 6379:6379
    restart: always
    container_name: tujr-redis
    hostname: tujr-redis
    environment:
      REDIS_PASSWORD: 12345
    networks:
      - spring_cloud_default

  tujr-gateway:
    build:
      context: ./gateway
    restart: always
    ports:
      - 7573:7573
    container_name: gateway
    hostname: gateway
    image: gateway
    networks:
      - spring_cloud_default

  user-service:
    build:
      context: ./user-service
    restart: always
    container_name: user-service
    hostname: user-service
    image: user-service
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name: spring_cloud_default
    driver: bridge
