spring:
  profiles:
    active: dev

  application:
    name: gateway

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
      default-filters:
        - name: Retry
          args:
            retries: 1
            series:
              - SERVER_ERROR
            statuses:
              - OK
            methods:
              - DELETE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**

server:
  port: 7573
